stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - cp ${ENV} .env
  script:
    - docker build -t bot-image .
  only:
    - main


deploy-job:
  stage: deploy
  before_script:
    - cp ${ENV} .env
  script:
    - docker-compose -f docker-compose-ci.yml down || true
    - docker-compose -f docker-compose-ci.yml up -d
  only:
    - main
